import type { Platform } from "../types.js";

/**
 * All SocialCrawl platforms with ACTIVE endpoints, derived from the
 * backend registry. Generated by scripts/generate-data.ts — do not
 * hand-edit. Descriptions are maintained in that script.
 * Source: packages/social-api/src/registry/config.ts
 */
export const PLATFORMS: Platform[] = [
  {
    slug: "web",
    name: "Web Scraping",
    endpointCount: 22,
    social: false,
    description:
      "Full web scraping, search, and browser automation (Firecrawl-backed). Sync scrape (markdown/HTML/screenshot/links), web search with content, site URL mapping, and LLM structured extraction; async crawl, batch-scrape, and autonomous agent jobs with a unified poll/cancel jobs surface; stateful web monitors (change detection on a cadence, delivered to a webhook); interactive browser sessions (open a page, execute code, close); and document parsing. The stateful surface (jobs, monitors, sessions, crawl/batch/agent) is managed through the dedicated `socialcrawl_web` tool; the sync scrape/search/map/extract endpoints are also available there.",
  },
  {
    slug: "tiktok",
    name: "TikTok",
    endpointCount: 36,
    social: true,
    category: "major",
    description:
      "Profiles, videos, comments and replies (incl. direct comment lookup), on-screen video text extraction, keyword/hashtag/top/user/music search plus search suggestions, hashtag details, the trending feed (worldwide or the in-country For You feed), TikTok's own popular-hashtag and Top Videos leaderboards, audience demographics, followers, following, a user's liked videos, playlists and collections, place-tagged videos, effects and effect feeds, live streams, songs, video transcripts, profile region lookup, and the TikTok Ad Library (ad details, ad search).",
  },
  {
    slug: "instagram",
    name: "Instagram",
    endpointCount: 37,
    social: true,
    category: "major",
    description:
      "Profiles, account transparency details (profile/about), posts, reels, comments and comment replies (incl. direct comment lookup), story highlights, stories, tagged posts, location feeds, followers, following, similar accounts, post likers, post-reshare stats, reels/posts feeds with per-item share counts in one call (profile/reels/full, profile/posts/full), account engagement analytics, universal search across accounts/hashtags/places, popular-post search, reels/hashtag/profile/location/music search, username suggestions, trending reels and music, audio reels, embed HTML, and AI-powered media transcripts.",
  },
  {
    slug: "youtube",
    name: "YouTube",
    endpointCount: 29,
    social: true,
    category: "major",
    description:
      "Channels, videos, shorts, comments and replies, video sponsors, playlists and playlist items, community posts, keyword/hashtag/advanced search and autocomplete suggestions, trending videos and shorts, channel live streams, channel contact email and country lookup (channel/about — billed only when an address is returned), downloadable media files (audio, video, subtitles, thumbnails), batch video/channel/transcript lookups, and video transcripts.",
  },
  {
    slug: "twitter",
    name: "Twitter/X",
    endpointCount: 15,
    social: true,
    category: "major",
    description:
      "Profiles, tweets and their replies, tweet search and user search, a user's media tweets, followers, following, retweeters, communities, community tweets, video transcripts, and AI-powered natural-language X search via Grok with citations.",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    endpointCount: 45,
    social: true,
    category: "major",
    description:
      "Personal profiles and company pages, posts, reposts, reactions, group and company posts, post comments and replies, people and company-people search, structured profile sub-resources (experiences, educations, skills, honors, certifications, publications, volunteers, recommendations, interests, images, videos), the complete post-history archive walk (profile/posts/archive — 100 posts a page, metered per post), jobs (job search, company jobs, job details), company insights and job counts, groups, location/school/industry search, post transcripts, and the LinkedIn Ad Library (ad details, ad search).",
  },
  {
    slug: "facebook",
    name: "Facebook",
    endpointCount: 24,
    social: true,
    category: "major",
    description:
      "Pages, groups and group posts, posts, comments and replies, photos, reels (incl. the full reels feed with per-item view counts), events and event search, Marketplace (keyword search, location search, item details), video and ad transcripts, and the full Facebook Ad Library (ads, company ads, ad search, company search).",
  },
  {
    slug: "reddit",
    name: "Reddit",
    endpointCount: 14,
    social: true,
    category: "major",
    description:
      "Subreddit posts and details, single post detail, post comments, user profiles with their post and comment history, keyword / comment / media search, subreddit discovery search, the cross-source omni-search composite, and post video transcripts.",
  },
  {
    slug: "threads",
    name: "Threads",
    endpointCount: 6,
    social: true,
    category: "major",
    description:
      "Profiles, posts, post details, post comments, keyword search, and user search.",
  },
  {
    slug: "pinterest",
    name: "Pinterest",
    endpointCount: 5,
    social: true,
    category: "additional",
    description:
      "Pins, boards, user boards, keyword search, and Pinterest Save-Button counts for any URL (url-stats).",
  },
  {
    slug: "twitch",
    name: "Twitch",
    endpointCount: 4,
    social: true,
    category: "additional",
    description:
      "Streamer profiles, clip details, user videos, and broadcast schedules.",
  },
  {
    slug: "snapchat",
    name: "Snapchat",
    endpointCount: 2,
    social: true,
    category: "additional",
    description:
      "Public user profiles including subscriber count and bio, plus comments on Spotlight posts.",
  },
  {
    slug: "truthsocial",
    name: "Truth Social",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details.",
  },
  {
    slug: "telegram",
    name: "Telegram",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Public Telegram channel profiles, channel post feeds, and single post lookups.",
  },
  {
    slug: "kick",
    name: "Kick",
    endpointCount: 1,
    social: true,
    category: "additional",
    description:
      "Clip details including view count, duration, and category.",
  },
  {
    slug: "kwai",
    name: "Kwai",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details from Kwai (Kuaishou's international short-video app).",
  },
  {
    slug: "tiktokshop",
    name: "TikTok Shop",
    endpointCount: 5,
    social: true,
    category: "commerce",
    description:
      "TikTok Shop product details, product reviews, shop product listings, shop search, and creator showcases.",
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Web research via Perplexity Sonar — returns a grounded answer with cited source URLs.",
  },
  {
    slug: "google",
    name: "Google",
    endpointCount: 10,
    social: true,
    category: "utility",
    description:
      "Google web search, Google Ads Transparency Center (ad details, advertiser search, company ads), Google Business Profile (place info, extended cross-source reviews, owner updates, Q&A), and Google Travel hotels (search + rich hotel details).",
  },
  {
    slug: "amazon",
    name: "Amazon",
    endpointCount: 8,
    social: true,
    description:
      "Product search, full ASIN product details, on-page reviews, buy-box sellers and offers, Amazon shop/storefront pages, Best Sellers charts by category, current deals, and seller profiles — across ~13 Amazon marketplaces via the country parameter.",
  },
  {
    slug: "google_shopping",
    name: "Google Shopping",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Google Shopping product search, full product details, price history for a product, reviews aggregated across retailers, and per-seller offers with itemised pricing.",
  },
  {
    slug: "google_news",
    name: "Google News",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Real-time Google News SERP search — ranked headlines with source, snippet, and timestamp for any query. Backed by a primary news upstream with a DataForSEO Google News fallback and bidirectional query-derived source pinning.",
  },
  {
    slug: "finance",
    name: "Finance",
    endpointCount: 7,
    social: false,
    category: "utility",
    description:
      "Financial-instrument data — full quotes, ticker search by name, a markets overview (indices + top movers), instrument news, daily price-history bars, company financial statements, and options chains.",
  },
  {
    slug: "google_trends",
    name: "Google Trends",
    endpointCount: 3,
    social: false,
    description:
      "Google Trends interest data — `explore` returns interest-over-time (and optional geo/related breakdowns) for one or more terms; `rising` returns breakout/rising related queries for a term; `trending` returns Trending Now for a location, filtered by hour window, category, status and sort. Backed by DataForSEO Google Trends.",
  },
  {
    slug: "trustpilot",
    name: "Trustpilot",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "Trustpilot business search and company reviews — brand-reputation data keyed by company domain (shipping, refunds, support sentiment). For product reviews use amazon/reviews or google_shopping/reviews.",
  },
  {
    slug: "g2",
    name: "G2",
    endpointCount: 7,
    social: false,
    category: "commerce",
    description:
      "G2 software marketplace — product pages by slug or URL, product reviews, category product listings and the full category URL index, vendor (seller) profiles with their product catalogue, and a product URL index for crawling.",
  },
  {
    slug: "google_play",
    name: "Google Play",
    endpointCount: 9,
    social: false,
    description:
      "Google Play app search, full app details, app reviews with developer replies, store charts (top free/paid/grossing), a filterable app listings database, search suggestions, and categories/locations/languages reference data.",
  },
  {
    slug: "app_store",
    name: "Apple App Store",
    endpointCount: 9,
    social: false,
    description:
      "Apple App Store app search, full app details, app reviews, store charts (top free/paid/grossing for iPhone and iPad), a filterable app listings database, search suggestions, and categories/locations/languages reference data.",
  },
  {
    slug: "tripadvisor",
    name: "Tripadvisor",
    endpointCount: 16,
    social: false,
    category: "commerce",
    description:
      "Hotels, restaurants, attractions and cruise ships — search and full detail for each, plus traveler reviews with owner replies, review images, and cross-language auto-translation metadata. Also place lookup by URL, destination autocomplete, and the experience types available in a destination.",
  },
  {
    slug: "walmart",
    name: "Walmart",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Walmart product details, product reviews, keyword search, category browsing, and every seller offering a product — across Walmart marketplaces via the country parameter.",
  },
  {
    slug: "target",
    name: "Target",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Target product details by TCIN, product reviews, category browsing, the full category taxonomy, and store lookup near a location.",
  },
  {
    slug: "wayfair",
    name: "Wayfair",
    endpointCount: 3,
    social: false,
    category: "commerce",
    description:
      "Wayfair product search, product details by SKU, and customer reviews.",
  },
  {
    slug: "home_depot",
    name: "Home Depot",
    endpointCount: 4,
    social: false,
    category: "commerce",
    description:
      "Home Depot keyword product search, product details by item id or URL (store- and zip-aware pricing), product reviews with rating, verified-purchase, and free-text filters, and store lookup near a ZIP code.",
  },
  {
    slug: "ebay",
    name: "eBay",
    endpointCount: 2,
    social: false,
    category: "commerce",
    description:
      "eBay listing search — including sold and completed listings with realised sale prices and dates — and full listing details by item id, across eBay country sites.",
  },
  {
    slug: "etsy",
    name: "Etsy",
    endpointCount: 4,
    social: false,
    category: "commerce",
    description:
      "Etsy listings by id or URL, a shop's product catalogue, similar-listing recommendations, and search suggestions.",
  },
  {
    slug: "sephora",
    name: "Sephora",
    endpointCount: 11,
    social: false,
    category: "commerce",
    description:
      "Sephora product details, customer reviews, keyword search and search suggestions, category browsing with the root/child category tree, brand listings and per-brand products, store lookup near a coordinate, and per-SKU in-store availability.",
  },
  {
    slug: "aliexpress",
    name: "AliExpress",
    endpointCount: 9,
    social: false,
    category: "commerce",
    description:
      "AliExpress product details, keyword search, similar products, customer reviews, per-SKU shipping options, hot products, featured promotions and their product lists, and the category tree.",
  },
  {
    slug: "hm",
    name: "H&M",
    endpointCount: 6,
    social: false,
    category: "commerce",
    description:
      "H&M keyword product search and search suggestions, store listings by country, the supported countries/languages table, the category tree, and per-product supplier and factory disclosure.",
  },
  {
    slug: "kohls",
    name: "Kohl's",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Kohl's keyword product search, product reviews, product questions and answers, store lookup near a coordinate, and the category tree.",
  },
  {
    slug: "klarna",
    name: "Klarna",
    endpointCount: 18,
    social: false,
    category: "commerce",
    description:
      "Klarna's shopping comparison graph — product details and every merchant offer for a product, keyword search and suggestions, user reviews, professional reviews and review-score overviews, price history, side-by-side product comparison, category browsing with sub-categories, filters, popular keywords and buying guides, and store listings with their products and filters.",
  },
  {
    slug: "gumtree",
    name: "Gumtree",
    endpointCount: 11,
    social: false,
    category: "commerce",
    description:
      "Gumtree UK classifieds — listing search and details, similar listings, seller profiles and their active ads, search suggestions, trending searches, the category tree with per-category filters, and location autocomplete plus nearest-location lookup.",
  },
  {
    slug: "yelp",
    name: "Yelp",
    endpointCount: 5,
    social: false,
    category: "commerce",
    description:
      "Yelp business profiles by encid, business reviews, business search (compact and full-card variants), and search suggestions.",
  },
  {
    slug: "utility",
    name: "Utility",
    endpointCount: 4,
    social: true,
    category: "utility",
    description:
      "Free, zero-credit API self-discovery — list every endpoint (`endpoints`), get exact usage for any one of them (`endpoint`), a one-call quickstart (`quickstart`), and an AI-agent context payload (`llms`). Served in-process from the endpoint registry: no network call, no auth cost, 0 credits.",
  },
  {
    slug: "linktree",
    name: "Linktree",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Linktree link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "linkbio",
    name: "LinkBio",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Linkbio link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "linkme",
    name: "LinkMe",
    endpointCount: 1,
    social: true,
    description:
      "Linkme link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "komi",
    name: "Komi",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Komi link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "pillar",
    name: "Pillar",
    endpointCount: 1,
    social: true,
    category: "linkPages",
    description:
      "Pillar link-in-bio pages including display name, bio, avatar, and link list.",
  },
  {
    slug: "polymarket",
    name: "Polymarket",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Prediction-market research — a server-side fan-out that expands a topic across multiple queries and ranks the merged Polymarket events.",
  },
  {
    slug: "hackernews",
    name: "Hacker News",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Story search, story details, story comment trees, and user profiles. Backed by the public Algolia HN API.",
  },
  {
    slug: "quora",
    name: "Quora",
    endpointCount: 7,
    social: true,
    category: "additional",
    description:
      "Question search and question details, answer search, Space post search, profile search, and Space/topic search.",
  },
  {
    slug: "douyin",
    name: "Douyin",
    endpointCount: 8,
    social: true,
    category: "additional",
    description:
      "Douyin (China's TikTok) — video search, creator profiles and their video feeds, single video detail, video comments and comment replies, creator search, and the hot-search trending board. Most lanes are metered per row returned, so cap `limit` before you call.",
  },
  {
    slug: "github",
    name: "GitHub",
    endpointCount: 12,
    social: false,
    category: "utility",
    description:
      "Users, repositories, user repos, READMEs, releases, issues, pull requests, issue/PR comments, issue/PR search, and composite repo top-issues/dossier + user profile-velocity reports. Backed by the official GitHub REST API.",
  },
  {
    slug: "tavily",
    name: "Tavily",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Web search with optional LLM-synthesised answer, content extraction from URLs, lightweight sitemap discovery, and full multi-page crawl.",
  },
  {
    slug: "naver",
    name: "Naver",
    endpointCount: 14,
    social: true,
    category: "utility",
    description:
      "Korea's #1 search portal — search corpora (blog, news, encyclopedia, cafe article, Q&A/KiN, local places, image, web), the Korean-language errata and adult-term classifiers, and Naver Data Lab search-trend + shopping-insight time series.",
  },
  {
    slug: "rumble",
    name: "Rumble",
    endpointCount: 5,
    social: true,
    category: "additional",
    description:
      "Video search, channel videos, video details, video comments, and video transcripts.",
  },
  {
    slug: "bluesky",
    name: "Bluesky",
    endpointCount: 3,
    social: true,
    category: "additional",
    description:
      "Profiles, user posts, and post details from the AT Protocol social network.",
  },
  {
    slug: "spotify",
    name: "Spotify",
    endpointCount: 6,
    social: true,
    category: "additional",
    description:
      "Artists, tracks, albums, podcasts, podcast episodes, and search across the Spotify catalog.",
  },
  {
    slug: "apple_music",
    name: "Apple Music",
    endpointCount: 4,
    social: true,
    category: "additional",
    description:
      "Apple Music catalog search plus artist, album, and track details.",
  },
  {
    slug: "search",
    name: "Universal Search",
    endpointCount: 4,
    social: false,
    category: "utility",
    description:
      "Meta-search lanes: `everywhere` fuses 14 platforms (up to 17 sources in hashtag mode) in a single flat-priced call; `forums` fuses Reddit + Hacker News + Naver KiN/Cafe with top comments inline; `news` plans, localizes, and fans a query out across up to 12 Google News country editions with metered per-leg billing; `creators` fuses TikTok + Threads + Instagram creator discovery, ranked by relevance, followers and verification. LLM-planned, RRF-fused, LLM-reranked, clustered.",
  },
  {
    slug: "prism",
    name: "Prism",
    endpointCount: 33,
    social: false,
    description:
      "Cross-platform composite intelligence — server-side recipes that fan out across many platforms and fold the legs into one unified report. Universal URL lookup, full comment harvesting, brand-mention and consumer-demand nowcasts, AI share-of-voice / GEO monitoring, crisis radar and post-mortems, cross-source reputation, share-of-voice, creator vetting and creator cards, handle audits, multi-engine AI consensus answers, org/repo radar, Korea gap analysis, and video/app/product intelligence. Each composite emits a per-leg transparency array; pricing is flat or metered per recipe (see the pricing docs topic and the socialcrawl_pricing tool).",
  },
  {
    slug: "content_analysis",
    name: "Content Analysis",
    endpointCount: 10,
    social: false,
    description:
      "Cross-web brand-mention search and 6-axis sentiment intelligence over news, blogs, ecommerce, and message boards — paginated mention feeds, sentiment/summary aggregates, rating distributions, phrase and category trends, plus languages/locations/categories/filters reference data.",
  },
  {
    slug: "on_page",
    name: "On-Page",
    endpointCount: 1,
    social: false,
    category: "utility",
    description:
      "Single-URL on-page SEO audit — the technical, content, and meta checks for one page in one call.",
  },
  {
    slug: "jobs",
    name: "Jobs",
    endpointCount: 11,
    social: false,
    category: "utility",
    description:
      "Job listings across LinkedIn, Indeed, Bing and Xing — keyword/location search plus single-listing detail for each, LinkedIn organization-id resolution, and salary ranges by job title and country with title suggestions.",
  },
  {
    slug: "us_congress_trades",
    name: "US Congress Trades",
    endpointCount: 19,
    social: false,
    category: "utility",
    description:
      "US Congress STOCK Act disclosures — searchable trade feeds (all, latest 48h, recent 7d), the members who have disclosed, per-politician summaries and trades, per-ticker stats and trades, per-state delegation trades, and the full statistics suite: party comparison, sectors, issuers, most-active politicians, most-traded tickers, volume over time, unusual activity, buy/sell ratio, and late-filing reporting gaps.",
  },
];

export function findPlatform(slug: string): Platform | undefined {
  return PLATFORMS.find((p) => p.slug === slug);
}

export function getAllPlatformSlugs(): string[] {
  return PLATFORMS.map((p) => p.slug);
}
