/**
 * Registry-wide counts and constants, mirrored from the backend's
 * REGISTRY_STATS / CreditCost / CacheTTL. Generated by
 * scripts/generate-data.ts — do not hand-edit.
 * Source: packages/social-api/src/registry/config.ts
 */

/** Live platform / endpoint / tier counts from the backend registry. */
export const REGISTRY_STATS = {
  "totalEndpoints": 575,
  "totalPlatforms": 65,
  "socialPlatforms": 31,
  "universalSearchPlatforms": 14,
  "universalSearchSources": 17,
  "standardEndpoints": 329,
  "advancedEndpoints": 211,
  "premiumEndpoints": 35,
  "standardLadder": 258,
  "advancedLadder": 166,
  "premiumLadder": 19,
  "customCount": 132
} as const;

/** The credit-tier ladder. Endpoints may override it flat or meter per query. */
export const CREDIT_LADDER: Record<string, number> = {
  "standard": 1,
  "advanced": 5,
  "premium": 10
};

/** Response-cache TTL (seconds) per category. A cache hit costs 0 credits. */
export const CACHE_TTLS: Record<string, number> = {
  "profile": 900,
  "post": 600,
  "comments": 300,
  "search": 120,
  "analytics": 1800,
  "immutable": 2592000
};
