/**
 * Registry-wide counts and constants, mirrored from the backend's
 * REGISTRY_STATS / CreditCost / CacheTTL. Generated by
 * scripts/generate-data.ts — do not hand-edit.
 * Source: packages/social-api/src/registry/config/
 */

/**
 * SHA-256 over every active endpoint's method, path and parameter names, as
 * the backend computes it (`docs/registry-dump.ts`). Two catalogues with the
 * same fingerprint accept exactly the same calls; the freshness check compares
 * it with the live API's.
 */
export const REGISTRY_FINGERPRINT = "5716804ad8c7ebd52245974b79d756890ccfa7cf3eec38c56cc2c0d3c4f55919";

/** Live platform / endpoint / tier counts from the backend registry. */
export const REGISTRY_STATS = {
  "totalEndpoints": 631,
  "totalPlatforms": 67,
  "socialPlatforms": 32,
  "universalSearchPlatforms": 14,
  "universalSearchSources": 17,
  "standardEndpoints": 347,
  "advancedEndpoints": 240,
  "premiumEndpoints": 44,
  "standardLadder": 239,
  "advancedLadder": 167,
  "premiumLadder": 25,
  "customCount": 200
} as const;

/** The credit-tier ladder. Endpoints may override it flat or meter per query. */
export const CREDIT_LADDER: Record<string, number> = {
  "standard": 1,
  "advanced": 5,
  "premium": 10
};

/** Response-cache TTL (seconds) per category. A cache hit costs 0 credits. */
export const CACHE_TTLS: Record<string, number> = {
  "profile": 900,
  "post": 600,
  "comments": 300,
  "search": 120,
  "analytics": 1800,
  "immutable": 2592000
};
